### ISSUE TITLE
Deploy fails/dashboard inaccessible

### ISSUE THREAD

**Issue by knownasilya** [pagefront/ember-pagefront#12]
Just tried a deploy today and it fails every time.

``` shell
ember deploy production

version: 1.13.13
- Preparing for deploy...
[object Object]
undefinedPipeline aborted
```
## It's not very descriptive. 

Looks like an API issue with the server 

> XMLHttpRequest cannot load https://api.pagefronthq.com/user. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dashboard.pagefronthq.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by jasonkriss** [comment]
@knownasilya Thanks for reporting this. Two issues here... First of all, that is a terribly unhelpful error message. Second, we experienced a lil hiccup with our API servers. This is now fixed, so you should be able to deploy now. No app servers were affected.

Sorry for the trouble on this!

**Comment by knownasilya** [comment]
:+1: on the fixed deploy. Anything that can be done about the message on your side? or is this all ember-cli-deploy?

**Comment by jasonkriss** [comment]
There is definitely something we can do to improve that on our side. the "[object Object]
undefinedPipeline aborted" is from ember-cli-deploy but we are able to diplay a helpful error message prior to that. Which we will!
