### ISSUE TITLE
Deprecation warning in Ember 2.x apps

### ISSUE THREAD

**Issue by balinterdi** [pagefront/ember-pagefront#13]
If `ember-pagefront` runs in an Ember 2 app (Ember 2.2.0, to be precise), the following deprecation warning is printed to the console:

> The `initialize` method for Application initializer 'pagefront-beacon' should take only one argument - `App`, an instance of an `Application`

**Comment by jasonkriss** [comment]
@balinterdi Which version of ember-pagefront are your using? This should be fixed in the latest version 0.10.10. Let me know if that isn't the case though. Thanks!

**Comment by balinterdi** [comment]
Turns out I'm still using 0.8.5. I'll update to the latest version and report back if that's still an issue (or close this issue if it is not). Thank you.

**Comment by jasonkriss** [comment]
Awesome. Thanks a lot @balinterdi !

**Comment by balinterdi** [comment]
The latest version works perfectly, without deprecation warnings. Thank you.

**Comment by jasonkriss** [comment]
Awesome! Thanks for following up @balinterdi.
