### ISSUE TITLE
Can a Personal app be transferred to an organization?

### ISSUE THREAD

**Issue by balinterdi** [pagefront/ember-pagefront#16]
I would like to transfer the rarwe app to the rarwe organization. Is there a way to achieve this?

![transfer app ownership](https://monosnap.com/file/3gyKgEuZDqdOPKWmCs0pxWGNE9KEkm.png)

Thank you.

**Comment by jasonkriss** [comment]
Indeed there is! Apologies for this not being documented yet but here's what you need to do...
1. Navigate to https://dashboard.pagefronthq.com/apps/rarwe/settings
2. Scroll down to "Transfer App" and click the "Transfer..." button
3. Enter your own email (I assume you are the admin of the rarwe organization) and click "Initiate Transfer"
4. Check your email and follow the link given
5. Select rarwe when it asks you "Who should own the app?"

We will be making this much easier for cases like this where you are transferring apps between your account and/or organizations you control. Also, we will be adding docs for this soon. Let me know if you have any other issues. Thanks!

**Comment by balinterdi** [comment]
Perfect, thank you, Jason.
