### ISSUE TITLE
"That app name has already been taken"

### ISSUE THREAD

**Issue by andershelmsworth** [pagefront/ember-pagefront#18]
Good day,

I'm trying to deploy an ember app using this utility, and when I run the command:

`ember install ember-pagefront --app=YOUR_UNIQUE_APP_NAME`

every string I supply as the app name argument is rejected with the following message:

`Darn. That app name has already been taken. Try again with a new name: ...`

I've gone so far as to generate random hexadecimal strings, and concatenate several together, to no avail. When I check what should be the URL of the page front app with that supposedly taken name, it doesn't exist. I believe there's some part of this project that checks existing names, which is broken. Please let me know if I can help test or supply any further information, and have a great day.

Cheers!

**Comment by jasonkriss** [comment]
Hey @andyhelmsworth! Sorry it was giving you trouble there. I just tested it out and was able to install and deploy without any trouble no. Must have just been a temporary issue maybe? You mind giving it another try and reporting back? I'm gonna close this for now but I'll reopen if you are still running into it.

Thanks a lot!

**Comment by andershelmsworth** [comment]
Hi @jasonkriss, thank you very much for looking into this. Unfortunately, I am still running into the error. If this helps troubleshoot at all, here are the steps I am taking:
- Start menu, type `cmd`, right-click and run command prompt as Administrator
- `$ cd` until I'm in the directory of my ember project, the same one from which i can run `$ ember serve` - said directory is almost at the root of the C:\ drive, if that makes a difference.

`$ ember install ember-pagefront --app=YRTLrarwe`

`>>DEPRECATION:`ember-cli/lib/errors/silent.js`is deprecated, use`silent-error`instead.`

`>>The option '--app' is not registered with the install command. Run`ember install --help`for a list of supported options.`

`>>Installed packages for tooling via npm.`

`>>installing ember-pagefront`

`>>Darn. That app name has already been taken. Try again with a new name:`ember g ember-pagefront --app=YOUR_APP_NAME``

Since that doesn't work, I try the specified command with a more complex app name, in this case a long, random hex string:

`C:\__EMBERBATCH2\rarwe>ember g ember-pagefront --app=2D65398F136A75CC5E544CCAAF`

`>>DEPRECATION:`ember-cli/lib/errors/silent.js`is deprecated, use`silent-error`instead.`

`>>installing ember-pagefront`

`Darn. That app name has already been taken. Try again with a new name:`ember g ember-pagefront --app=YOUR_APP_NAME``

Hopefully this helps. Happy to provide any further information that might be useful. Again, thanks so much for your assistance!
