### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jtsom** [pagefront/ember-pagefront#4]
If this is the package for www.pagefronthq.com, then there are problems trying to load the package, using the (somewhat sparse) docs:

ember install ember-pagefront --app=mindstorm
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
The option '--app' is not registered with the install command. Run `ember install --help` for a list of supported options.
Installed packages for tooling via npm.
installing ember-pagefront
  install package ember-cli-deploy
Installed packages for tooling via npm.
  create .pagefrontrc
  create config/deploy.js
key is not defined (Error in blueprint template: /Users/john/Devel/ember/mindstorm/node_modules/ember-pagefront/blueprints/ember-pagefront/files/.pagefrontrc)
ReferenceError: key is not defined (Error in blueprint template: /Users/john/Devel/ember/mindstorm/node_modules/ember-pagefront/blueprints/ember-pagefront/files/.pagefrontrc)
    at eval (eval at <anonymous> (/Users/john/Devel/ember/mindstorm/node_modules/ember-cli/node_modules/lodash/string/template.js:214:12), <anonymous>:8:11)
    at processTemplate (/Users/john/Devel/ember/mindstorm/node_modules/ember-cli/lib/models/file-info.js:13:52)
    at /Users/john/Devel/ember/mindstorm/node_modules/ember-cli/lib/models/file-info.js:94:20
    at lib$rsvp$$internal$$tryCatch (/Users/john/Devel/ember/mindstorm/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/john/Devel/ember/mindstorm/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/john/Devel/ember/mindstorm/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/john/Devel/ember/mindstorm/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by jasonkriss** [comment]
I think even calling the docs sparse right now is quite generous of you :smile:!

Sorry you ran into issues here! This is definitely a bug, in that the error messages need to be much more clear about what is happening and what you can do to fix it. I'm gonna leave this issue open until that is corrected.

In the meantime, you can fix this by first creating the mindstorm app in the pagefront dashboard. Once you do that, it will show you a full install command that you can copy and paste into the terminal. That should get you going.

Thanks a lot for reporting this! Feel free to shoot me an email at jason@pagefronthq.com if you have any questions at all.

**Comment by jtsom** [comment]
Thanks. I used the command given when I created the app on the dashboard. While it didn't throw the errors above, it does still give:

```
The option '--app' is not registered with the install command. Run `ember install --help` for a list of supported options.
The option '--key' is not registered with the install command. Run `ember install --help` for a list of supported options.
```

**Comment by jasonkriss** [comment]
Another valid issue. Those are just warnings, so you can safely ignore them. However, it is indeed another thing we need to get rid of. Thanks for pointing it out!

Glad you got it installed now though. Thanks for following up!

**Comment by jtsom** [comment]
Having more problems installing. Wanted to get up to date. First attempt was to update the version in the package.json file and 'npm install'. That seemed to install, but trying to do an 'ember deploy' failed with:

```
- Missing required config: `key`
|
+- didFail
Error: Missing required config: `key`
Error: Missing required config: `key`
    at Class.CoreObject.extend.ensureConfigPropertySet (/Users/John/Dev/Ember/mindstorm/node_modules/ember-cli-deploy-plugin/index.js:41:13)
```

Attempting to reinstall ('npm uninstall' followed by ember install...) fails with:

```
ember install ember-pagefront --app=mindstorm
version: 1.13.13
The option '--app' is not registered with the install command. Run `ember install --help` for a list of supported options.
Installed packages for tooling via npm.
installing ember-pagefront
  install package ember-cli-deploy
Installed packages for tooling via npm.
  create .env.deploy.production
  identical config/deploy.js
key is not defined (Error in blueprint template: /Users/John/Dev/Ember/mindstorm/node_modules/ember-pagefront/blueprints/ember-pagefront/files/.env.deploy.production)
ReferenceError: key is not defined (Error in blueprint template: /Users/John/Dev/Ember/mindstorm/node_modules/ember-pagefront/blueprints/ember-pagefront/files/.env.deploy.production)
```

**Comment by jtsom** [comment]
Ugh. My bad (mostly). I forgot to add the --key= to the ember install command. Once I did that, it all worked.

**Comment by jasonkriss** [comment]
@jtsom Sorry for the confusion on that. That's definitely still our fault. These are not things you should have to be thinking about at all. We will improve this process, it's just a matter of time. I apoligize that it has taken so long.

**Comment by jasonkriss** [comment]
@jtsom Just wanted to follow up on this. As of 0.10.9, it is now possible to simply `ember install ember-pagefront --app=mindstorm` and `ember deploy production`. No need to create the app in the dashboard first. We've also done a lot fo work to improve the error messages and make it much more obvious what is going wrong.

I'm Gonna go ahead and close this issue now but please let me know if you have any other issues. Thanks for your help on all this!
